version: '3.1'

services:
  mariadb1058:
    container_name: 'mariadb1058'
    image: mariadb:10.5.8
    ports: 
      - '${MARIADB_1058_PORT}:3306'
    volumes: 
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_1058_ROOT_PASSWORD}
      MYSQL_USER: ${MARIADB_1058_USER}
      MYSQL_PASSWORD: ${MARIADB_1058_PASSWORD}
    restart: unless-stopped

networks:
  default:
    external:
      name: dockernet