version: '3.1'

services:
  php70:
    container_name: 'php70'
    build: './'
    ports:
      - '${PHP_70_PORT}:9000'
    volumes:
      - '${PHP_70_WEBROOT}:/webroot'
    restart: unless-stopped
networks:
  default:
    external:
      name: dockernet