version: '3.1'

services: 
  mysql56:
    container_name: 'mysql56'
    platform: "linux/x86_64"
    build: "./"
    ports: 
      - '${MYSQL_56_PORT}:3306'
    volumes: 
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_56_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_56_USER}
      MYSQL_PASSWORD: ${MYSQL_56_PASSWORD}
    restart: unless-stopped
networks:
  default:
    external:
      name: dockernet