version: '3.1'

services:
  php56:
    container_name: 'php56'
    build: './'
    ports:
      - '${PHP_56_PORT}:9000'
    volumes:
      - '${PHP_56_WEBROOT}:/webroot'
    restart: unless-stopped
networks:
  default:
    external:
      name: dockernet