version: '3.1'

services:
  plex:
    container_name: 'plex'
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=${PLEX_TIMEZONE}
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    # network_mode: host
    volumes:
      - ./data/config:/config
      - ./data/transcode:/transcode
      - ${PLEX_MEDIA_LOCATION}:/data
    ports:
      - "32400:32400"
      - "3005:3005"
      - "8324:8324"
      - "32469:32469"
      - "1900:1900"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"