version: '3'

services:
  mongo:
    image: 'mongo'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INIT_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./data:/data/db
    ports:
      - '27017-27019:27017-27019'
    restart: unless-stopped
networks:
  default:
    external:
      name: dockernet