version: '3.1'

services: 
  mysql80:
    container_name: 'mysql80'
    platform: "linux/x86_64"
    build: "./"
    ports: 
      - '${MYSQL_80_PORT}:3306'
    volumes: 
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_80_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_80_USER}
      MYSQL_PASSWORD: ${MYSQL_80_PASSWORD}
    restart: unless-stopped
networks:
  default:
    external:
      name: dockernet