version: '3.1'

services:
  php54:
    container_name: 'php54'
    build: './'
    ports:
      - '${PHP_54_PORT}:9000'
    volumes:
      - '${PHP_54_WEBROOT}:/webroot'
    restart: unless-stopped
networks:
  default:
    external:
      name: dockernet