version: '2'

services:
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    ports:
      - ${NEXTCLOUD_PORT}:80
    volumes:
      - ./data/html:/var/www/html
      - ./data/apps:/var/www/html/custom_apps
      - ./data/config:/var/www/html/config
      - ./data/data:/var/www/html/data
    environment:
      - SQLITE_DATABASE=nextcloud.sqlite