version: '3.1'

services: 
  elasticstash:
    container_name: 'elasticstash'
    image: 'docker.elastic.co/logstash/logstash:7.14.1'
    ports: 
      - '9200:9200'
    volumes: 
      - ./data:/usr/share/logstash/pipeline/
    restart: unless-stopped
networks:
  default:
    external:
      name: dockernet