version: '3.1'

services:
  php55:
    container_name: 'php55'
    build: './'
    ports:
      - '${PHP_55_PORT}:9000'
    volumes:
      - '${PHP_55_WEBROOT}:/webroot'
    restart: unless-stopped
networks:
  default:
    external:
      name: dockernet