version: '3.1'

services:
  rabbitmq:
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    image: rabbitmq:3.9.5-management
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/rabbitmq
    ports: 
      - "15672:15672"
networks:
  default:
    external:
      name: dockernet