version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin
    container_name: 'phpmyadmin'
    restart: unless-stopped
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
networks:
  default:
    external:
      name: dockernet