version: '3.1'

services:
  nginx:
    container_name: 'nginx'
    hostname: 'nginx'
    image: nginx:1.21
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${NGINX_WEBROOT}:/webroot:ro
    ports: 
      - "${NGINX_PORT}:80"
networks:
  default:
    external:
      name: dockernet