version: '3.1'

services:
  php72:
    container_name: 'php72'
    build: './'
    ports:
      - '${PHP_72_PORT}:9000'
    volumes:
      - '${PHP_72_WEBROOT}:/webroot'
    restart: unless-stopped
networks:
  default:
    external:
      name: dockernet